[project]
name = "sample-python-project"
version = "1.0.1"
description = "A sample project for GitHub Actions with pytest"
dependencies = [
    "urllib3==2.5.0"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

